### PR TITLE
Format subunit content pages

### PR DESCRIPTION
**Pull request by Rino-DG**
Screenshot 2024-03-27 at 8 47 03 AM
Screenshot 2024-03-2
![Screenshot 2024-03-27 at 9 10 51 AM
7 at 9 10 37 AM](https://github.com/baileyrosato/Anatomia/assets/102436048/16ac7a95-d632-48a3-aa3f-64a099ba26a5)

This resolves issue #138 . Had to add the html-react-parser package, hopefully it works well in your machines as well!

### CODE REVIEW

**Review by nicolesylvester — APPROVED** [review]
Looks great! Would you be able to update the descriptions with the html tags in the dataInit file as well so that the online database and the file matches?

**Comment by Rino-DG** [comment]
> Looks great! Would you be able to update the descriptions with the html tags in the dataInit file as well so that the online database and the file matches?

Will do!

**Review by dayraquin — APPROVED** [review]
Looks great to me!!

**Comment by baileyrosato** [comment]
PR merged 4/2/24

**Pull request merged**
