### PR TITLE
Added planes of sectioning options

### LINKED ISSUE #130: Planes of Sectioning
Adding the different planes to the application.
Allowing users to be able to add a plane to the model by pressing the corresponding button.

### LINKED ISSUE #133: Model refresh for new subunits
After adding new interactivity to the models for specific subunits, there is an issue where the directional terms is maintained across all subunits and prevents the user from rotating the model in other subunits.

### PR DESCRIPTION
**Pull request by nicolesylvester**

### CODE REVIEW

**Comment by baileyrosato** [comment]
Hey! It looks great, just one small problem: when the planes are on the model and a different subunit is selected the plane stays on the model. And you cannot remove it unless you go back to the correct subunit or refresh.

**Comment by nicolesylvester** [comment]
3/13: fixed planes and camera to reset when changing subunits.

**Review by dayraquin — APPROVED** [review]

**Review by baileyrosato — APPROVED** [review]
Looks great!! Works for me

**Comment by baileyrosato** [comment]
PR merged 3/14

**Pull request merged**
