### PR TITLE
View full subunit image

### PR DESCRIPTION
**Pull request by nicolesylvester**
if you click on a subunit image, it expands full screen so the user can view the whole image.

### CODE REVIEW

**Review by baileyrosato — APPROVED** [review]
Looks good!

**Review by Rino-DG — APPROVED** [review]
Works great for me!
Screenshot 2024-02-27 at 1 47 32 PM

**Review by dayraquin — APPROVED** [review]
Works for me!

**Comment by baileyrosato** [comment]
PR merged 2/27

**Pull request merged**
