### PR TITLE
Whiteboard feature on subunit page

### LINKED ISSUE #124: Add whiteboard feature to subunit page

### PR DESCRIPTION
**Pull request by nicolesylvester**

### CODE REVIEW

**Comment by nicolesylvester** [comment]
need to install tldraw which is the whiteboard we are using to avoid errors, run npm install @tldraw/tldraw@beta to download

**Review by baileyrosato — APPROVED** [review]
Looks good to me!

**Review by dayraquin — APPROVED** [review]
Works for me!

**Comment by Rino-DG** [comment]
Screenshot 2024-03-01 at 8 01 12 AM
Looks good to me!

**Pull request merged**
